### ISSUE TITLE
Provide binding.caller_of_caller or default to caller of caller.

### ISSUE THREAD

**Issue by envygeeks** [banister/binding_of_caller#3]
Right now when rescuing into debuggers we have to do binding.of_caller(n) which could confuse the user as to what we are exactly doing if they don't know about binding_of_caller.  It would be nice to imply what we are doing by having binding.caller_of_caller so the user could see that hey we are putting them into the context of the caller so they can debug the area that had an exception.

There is another small tidbit (but we can address that ourselves with an internal function) which is detecting if the caller is inside of a rescue and if it is push it to the next caller -- but I don't know much about ruby internals to say if that's easy to implement.

**Comment by prpetten** [comment]
@envygeeks Are you still having this issue?   Trying to take over maintenance.
