### ISSUE TITLE
fails when gc.h file is on standard include path

### ISSUE THREAD

**Issue by skaes** [banister/binding_of_caller#42]
On a system, where a gc.h file is available, the gem is compiled properly.

Symptom:

dyld: lazy symbol binding failed: Symbol not found: _RUBY_FREE_ENTER

This is caused by finding a copy of boehm's gc.h before finding ruby's gc.h.

I'll submit a patch.

**Comment by prpetten** [comment]
Closing this as 1.9.3 is well past end of life.
