### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by schmijos** [banister/binding_of_caller#58]
It's not clear for me how I can run the tests of this gem. Could you explain that in the README please?

`rake test` fails for Ruby 2.2.2 on Mac OS X with the following message:

```
bacon -Itest -rubygems -a -q
rake aborted!
Command failed with status (127): [bacon -Itest -rubygems -a -q...]
/Users/josua/projects/binding_of_caller/Rakefile:54:in `block in <top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by Apteryks** [comment]
Seems you are missing the 'bacon' development dependency.

**Comment by schmijos** [comment]
Nice, 5 years later 🤣 

I got it running immediately

![image](https://user-images.githubusercontent.com/245443/85981813-18074380-b9e5-11ea-8fc8-835d5c45c7cf.png)

Still I'm not sure, why the binary is not around when installed with `bundle install`.
