### ISSUE TITLE
Simpler version

### ISSUE THREAD

**Issue by shreeve** [banister/binding_of_caller#62]
I just pushed a simpler version of this gem called `bindings`, which is available on rubygems. Just wanted to let others know, who might be looking for a simpler approach.

**Comment by shreeve** [comment]
The link is https://github.com/shreeve/bindings

**Comment by 007lva** [comment]
Nice to see your gem. It could work with [better_errors](https://github.com/charliesome/better_errors) as binding_of_caller do?
