### ISSUE TITLE
Rails stops responding after editing a Helper file that builds an HTML layout

### ISSUE THREAD

**Issue by seanjhulse** [banister/binding_of_caller#65]
**Rails 5.1.4**

**Ruby 2.3.5**

While the server is running and I will attempt to edit a custom Helper (which builds a layout). After sending a GET request to refresh the page and see the layout changes, the application seizes up and stops responding. After removing 'binding of caller' from my Gemfile, it no longer has any issues showing my changes to the file. Despite trying to figure out a workaround, I have been unable to continue using Binding of Caller in my application.

For reference, this is my console output:

```bash
# better errors trying to resolve the broken helper method 
Started POST "/__better_errors/346947eb36a45685/variables" for ::1 at 2017-10-18 16:05:15 -0500

# GET request after I fix the helper method
Started GET "/admin/shoots?show=past" for ::1 at 2017-10-18 16:05:20 -0500
```

The log doesn't output anything else. The GET request is my attempt at reloading the page after making changes to the Helper file. But it just sits there indefinitely while the browser indefinitely waits for a response. 

After performing a ```kill -9 ${PID}``` to the PID, I am able to restart the server and my helper method compiles the HTML and my server responds. But until then, there is nothing I'm able to do on the application.

**Comment by rylanb** [comment]
I'm seeing issues like this, as well. My local dev server slowly becomes more and more unresponsive (takes longer and longer to load) until I have to kill the server and find the `puma` process via `ps aux | grep puma` and then `kill -9 ${PID}` 

Would love to know why and if its related to `boc` or something else. I've taken out `web-console` for now, which removes `boc`, experimenting to see if that helps

**Comment by RobinDaugherty** [comment]
Any indication that this is still an issue? Not sure if this is the Better Errors performance issues fixed in https://github.com/BetterErrors/better_errors/pull/402, or if it's something else.
