### ISSUE TITLE
Hides view error frames in rails 6

### ISSUE THREAD

**Issue by Karoid** [banister/binding_of_caller#75]
**Rails 6.0.3**

**Ruby 2.6.6**

While this gem is included in project, I can't see rails view error in Rails Error page. Following image is shown when gem is included in project
```
# Gemfile
group :development do
  gem 'binding_of_caller'
end
```
![image](https://user-images.githubusercontent.com/18082991/83223898-0bf64f00-a1b7-11ea-9eb3-a58c238bc735.png)
and this image is when I remove 'binding_of_caller' gem in project
```
# Gemfile
group :development do
  # gem 'binding_of_caller'
end
```
![image](https://user-images.githubusercontent.com/18082991/83224151-aeaecd80-a1b7-11ea-9fff-02c199449337.png)

It seems like there is some issue with code change in rails 6.

**Comment by mildred** [comment]
It seems to be https://github.com/BetterErrors/better_errors/issues/466 (and not the fault of binding_of_caller)

**Comment by RobinDaugherty** [comment]
Yes, this should be fixed by https://github.com/BetterErrors/better_errors/pull/477
