### ISSUE TITLE
When starting rails it cannot load with ruby 3.0.0-preview1

### ISSUE THREAD

**Issue by deezzer** [banister/binding_of_caller#77]
When trying to start the rails server with ruby 3.0.0-preview1, it won't start unless binding_of_caller is removed from the gemset. Here are the logs: 

/me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require': cannot load such file -- binding_of_caller.bundle (LoadError)
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/binding_of_caller-0.8.0/lib/binding_of_caller.rb:9:in `<top (required)>'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:66:in `require'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /me/.rvm/rubies/ruby-3.0.0-preview1/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /me/Apps/reactisviewcancer/config/application.rb:21:in `<top (required)>'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	from /me/Apps/reactisviewcancer/vendor/bundle/ruby/3.0.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'

**Comment by christiannelson** [comment]
Happy Holidays! Confirming that this remains an issue with ruby-3.0.0 (final)...

```
rails aborted!
LoadError: cannot load such file -- binding_of_caller.bundle
/Users/christian/Projects/carbon-five/raygun-rails/config/application.rb:20:in `<main>'
/Users/christian/Projects/carbon-five/raygun-rails/Rakefile:4:in `<main>'
/Users/christian/Projects/carbon-five/raygun-rails/bin/rails:5:in `<top (required)>'
<internal:/Users/christian/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/christian/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

**Comment by walski** [comment]
See https://github.com/banister/binding_of_caller/pull/81

**Comment by kapso** [comment]
Hey guys, any plans for getting ruby 3.0.0 support?

Thanks.

**Comment by RobinDaugherty** [comment]
As of [1.0.0](https://github.com/banister/binding_of_caller/releases/tag/v1.0.0), Ruby 3.0 is supported. Looks like we forgot to close this issue!
