### ISSUE TITLE
binding.call(1).break not valid on debug gem which was builtin on Ruby 3.1release.

### ISSUE THREAD

**Issue by zw963** [banister/binding_of_caller#83]
I want warp offical `binding.break` into a method, assume, named: `brk!`.

following is attempt: (compare to pry)

```rb
require 'binding_of_caller'

class Binding
  def _break
    require 'debug'

    warn 'laoding break'

    self.break
  end

  def _pry
    require 'pry'
    warn 'loading pry'
    self.pry
  end
end

class Object
  def brk!
    binding.of_caller(1)._break
  end

  def pry!
    binding.of_caller(1)._pry
  end
end

```

What i expected is, wrappered brk! behavior like wrapped pry!.

e.g.  asssume, we have 1.rb code like this:

```rb
puts 100
pry!
puts 200
```

when run with `ruby 1.rb`, get this: (it was expected)

![image](https://user-images.githubusercontent.com/549126/147952576-2eb7f62f-9dbc-4da7-9cf4-88d4f2535b53.png)

But, when if change code to this:

```rb
puts 100
brk!
puts 200
```

when run `ruby 1.rb`, get this. (it was unexpected)

![image](https://user-images.githubusercontent.com/549126/147952826-474e0189-b9ba-47ac-a3d0-730c2a5c8d1a.png)

as you can see, the `=>` not stop on correct position. (which we expected to on same line as brk! as pry! does)

Thank you.

**Comment by zw963** [comment]
for debug gem, please check here

https://github.com/ruby/debug

**Comment by badosu** [comment]
You can add some print lines and it might work.

Sometimes it does not work in the same stack as the pry call, for pure debugging some other gems might do the work better.

**Comment by zw963** [comment]
> You can add some print lines and it might work, e.g. `binding.pry \n puts 'break'`
> 
> Sometimes it does not work in the same stack as the pry call, for pure debugging some other gems might do the work better.
> 
> You and also go up and down the frame stack but that often get cumbersome.

Hi, it seem like not work?

![image](https://user-images.githubusercontent.com/549126/148501963-2d0bb705-1b46-4254-b4ae-782bd383c558.png)

_break method is defined on Binding class, i add a `puts '1'`, invoke it from brk! method use ` binding.of_caller(1)._break`,  it still stop there.

**Comment by badosu** [comment]
I've never used `break`. For debugging there used to be specific gems tied to Pry (like https://github.com/nixme/pry-debugger).

This seems to be the last one supported: https://github.com/nixme/pry-debugger

**Comment by zw963** [comment]
> I've never used `break`. For debugging there used to be specific gems tied to Pry (like https://github.com/nixme/pry-debugger).
> 
> This seems to be the last one supported: https://github.com/nixme/pry-debugger

In fact, binding_of_caller(1) not support by byebug too, because of this reason, i never use byebug in my project.

but, this time, `debug(binding.break)` is ruby builtin gem, so, i just curious if we can fix this to support it.

**Comment by prpetten** [comment]
@zw963 Did you ever find a workaround for this issue?

**Comment by zw963** [comment]
> @zw963 Did you ever find a workaround for this issue?

No, i use [pry-nav](https://github.com/zw963/pryx/blob/master/pryx.gemspec#L22) instead.

**Comment by prpetten** [comment]
Gotcha, I'm going to close this issue then for now.
